services:
  app:
    build: .
    container_name: nestjs_app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:docker@postgres:5432/teste-sga
      JWT_SECRET: secret
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: >
      sh -c "yarn prisma migrate deploy &&
             yarn start:prod"
    networks:
      - nestjs_network

  postgres:
    image: postgres:latest
    container_name: nestjs_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: teste-sga
    ports:
      - '5432:5432'
    networks:
      - nestjs_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: nestjs_redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - nestjs_network

networks:
  nestjs_network:
    driver: bridge

volumes:
  postgres_data:
